type: google.api.Service
config_version: 3
name: "*.apigateway.PROJECT_ID.cloud.goog"
title: Radwallet Service
apis:
  - name: radhark.radwallet.Auth
  - name: radhark.radwallet.Profile
authentication:
  providers:
  - id: google_service_account
    # Replace SERVICE-ACCOUNT-ID with your service account's email address.
    issuer: datastore-credentials@radwallet-dev.iam.gserviceaccount.com
    jwks_uri: https://www.googleapis.com/robot/v1/metadata/x509/datastore-credentials@radwallet-dev.iam.gserviceaccount.com
  - id: rad_auth
    issuer: radwallet
    jwks_uri: https://storage.googleapis.com/dev.radwallet.com.br/.well-known/jwks.json
    audiences: "radwallet-dev"
    jwt_locations:
    - header: "authorization"
      value_prefix: "Bearer "
  rules:
  - selector: "radhark.radwallet.Profile.*"
    requirements:
    - provider_id: rad_auth
  - selector: "radhark.radwallet.Exchange.*"
    requirements:
    - provider_id: rad_auth
  - selector: "radhark.radwallet.Profile.GetProfileInternal"
    requirements:
      - provider_id: google_service_account
usage:
  rules:
    - selector: "*"
      allow_unregistered_calls: true
backend:
  rules:
    - selector: "radhark.radwallet.Auth.*"
      address: grpcs://auth-5yx3hbvt6q-ue.a.run.app
    - selector: "radhark.radwallet.Profile.*"
      address: grpcs://profile-5yx3hbvt6q-ue.a.run.app